Onb 101 ilkim elif kervan
mobileaction-juniors/demo-multi-module-example-dev pull request #7
Opened 2023-07-07 13:54 UTC by elif-krvan

## Description

> Description here...

## Checklists

### Development and testing

- [ ] Related unit test have been implemented/updated
- [ ] Application changes have been tested locally
- [ ] Related documents have been updated

### Security

- [ ] Security impact of the change has been considered
- [ ] Code follows MobileAction's security practices and policies

### Code review 

- [ ] Pull request title follows [conventional commit format](https://mobileaction.atlassian.net/wiki/spaces/ENG/pages/743112854/Conventional+Commit+Messages) and has a JIRA task id

2023-07-10 07:08 UTC, halilsarial requested changes

2023-07-10 07:08 UTC, halilsarial commented on common/src/main/resources/application-common-dev.properties
You should add properties also to prod

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/queue/UserResultQueueHandler.java
> +            log.error("Could not handle result for postId: {}", result.getId(), e);
postId?

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/repository/IPostRepository.java
> +    @Transactional
Transactional annotation is used for managing transactions and generally it is used in service classes. If there are more than one sql operation, this annotation provides running or rolling back all operations together. It is not necessary for repository method.

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/repository/IPostRepository.java
> +    List<Long> findDistinctUserIds();
Set is better instead of list for keeping distinct values

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/queue/UserResultQueueHandler.java
> +
no need empty line between two class fields

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/IPostService.java
> +    void deleteUserPost(Long userId);
```suggestion
    void deleteUserPosts(Long userId);
```
Naming

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/IUserResultHandlerService.java
> +    void executeMessage(UserDto userDto) throws AlreadyExistException;
unnecessary throws defining

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/IUserService.java
> +    void saveUser(User user) throws AlreadyExistException;
unnecessary throws defining

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/PostResultHandlerService.java
> +                .userId(postDto.getId())
```suggestion
                .userId(postDto.getUserId())
```

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/UserQueueService.java
> +
empty line

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/UserQueueService.java
> +        userIds.stream().mapToLong(Long::longValue)
no need to mapToLong mapping

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/exception/BaseException.java
> +public class BaseException extends Exception
Extending RuntimeException is better

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/exception/BaseException.java
> +    private String message;
No need keeping message for this class. Parent class field can be used

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/exception/BaseException.java
> +        System.out.println(this.message);
You shouldn't use sout

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/exception/BaseException.java
> +    public String getMessage()
You can use lombok for getter, if there is no special code block in your getter/setter method

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/UserService.java
> +        boolean userAlreadyExists = userExist(user.getId());
No need assign to variable. You can user directly in if block.
```suggestion
        if (userExist(user.getId()))
```

2023-07-10 07:08 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/service/UserService.java
> +    public boolean userExist(Long id)
```suggestion
    public boolean userExists(Long id)
```

2023-07-10 07:08 UTC, halilsarial commented on worker/src/main/java/co/mobileaction/example/worker/WorkerAppConfig.java
> +    public AmqpTemplate userRequestProblemQueueTemplate(ConnectionFactory rabbitConnectionFactory,
reformat code

2023-07-10 07:08 UTC, halilsarial commented on worker/src/main/java/co/mobileaction/example/worker/queue/PostRequestQueueHandler.java
> +import co.mobileaction.example.common.dto.UserRequestDto;
unused import

2023-07-10 07:08 UTC, halilsarial commented on worker/src/main/java/co/mobileaction/example/worker/service/IPostRequestHandlerService.java
> +
unnecessary empty line

2023-07-10 07:08 UTC, halilsarial commented on worker/src/main/java/co/mobileaction/example/worker/service/PostRequestHandlerService.java
> +import co.mobileaction.example.common.dto.UserRequestDto;
unused import

2023-07-10 07:08 UTC, halilsarial commented on worker/src/main/java/co/mobileaction/example/worker/service/UserRequestHandlerService.java
> +            e.printStackTrace();
Use log.error instead of printStackTrace

2023-07-10 11:59 UTC, elif-krvan commented on web/src/main/java/co/mobileaction/example/web/service/UserService.java
> +        boolean userAlreadyExists = userExist(user.getId());
I think assigning to a new variable looks more readable

2023-07-10 12:28 UTC, elif-krvan commented on web/src/main/java/co/mobileaction/example/web/repository/IPostRepository.java
> +    @Transactional
without Transactional annotation delete method does not work

2023-07-11 08:01 UTC, halilsarial commented on web/src/main/java/co/mobileaction/example/web/exception/BaseException.java
> +public class BaseException extends RuntimeException
```suggestion
@Getter
@Setter
public class BaseException extends RuntimeException
```
You can use getter setter like that. No need extra getter setter definition (if there is no specific implementation)

2023-07-11 08:08 UTC, halilsarial approved these changes

2023-07-11 08:08 UTC, halilsarial approved these changes
@elif-krvan  Please don't merge the code. Time to deploy to heroku

2023-07-11 11:38 UTC, closed without merging